// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AnnonsContext))]
    [Migration("20260408114759_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnonsorId")
                        .HasColumnType("integer")
                        .HasColumnName("ad_ann_id");

                    b.Property<decimal>("Annonspris")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ad_annonspris");

                    b.Property<string>("Innehall")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad_innehall");

                    b.Property<string>("Rubrik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ad_rubrik");

                    b.Property<decimal>("Varupris")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("ad_varupris");

                    b.HasKey("Id");

                    b.HasIndex("AnnonsorId");

                    b.ToTable("tbl_ads");
                });

            modelBuilder.Entity("Annonsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ann_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FakturaAdress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ann_fakt_adress");

                    b.Property<string>("FakturaOrt")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ann_fakt_ort");

                    b.Property<string>("FakturaPostnummer")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ann_fakt_postnummer");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ann_namn");

                    b.Property<string>("Organisationsnummer")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ann_organisationsnummer");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ann_ort");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ann_postnummer");

                    b.Property<int?>("PreId")
                        .HasColumnType("integer")
                        .HasColumnName("ann_pre_id");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ann_telefonnummer");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ann_typ");

                    b.Property<string>("Utdelningsadress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ann_utdelningsadress");

                    b.HasKey("Id");

                    b.ToTable("tbl_annonsorer", null, t =>
                        {
                            t.HasCheckConstraint("ck_ann_typ", "ann_typ IN ('prenumerant', 'foretag')");
                        });
                });

            modelBuilder.Entity("Ad", b =>
                {
                    b.HasOne("Annonsor", "Annonsor")
                        .WithMany("Ads")
                        .HasForeignKey("AnnonsorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annonsor");
                });

            modelBuilder.Entity("Annonsor", b =>
                {
                    b.Navigation("Ads");
                });
#pragma warning restore 612, 618
        }
    }
}
