// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PrenumerantSystem.Migrations
{
    [DbContext(typeof(PrenumerantContext))]
    partial class PrenumerantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prenumerant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pre_efternamn");

                    b.Property<string>("Fornamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pre_fornamn");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pre_ort");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("pre_personnummer");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pre_postnummer");

                    b.Property<int>("Prenumerantnummer")
                        .HasColumnType("integer")
                        .HasColumnName("pre_prenumerantnummer");

                    b.Property<string>("Telefonnummer")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pre_telefonnummer");

                    b.Property<string>("Utdelningsadress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pre_utdelningsadress");

                    b.HasKey("Id");

                    b.HasIndex("Personnummer")
                        .IsUnique();

                    b.HasIndex("Prenumerantnummer")
                        .IsUnique();

                    b.ToTable("tbl_prenumeranter");
                });
#pragma warning restore 612, 618
        }
    }
}
